version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'mnemonic_trainer_development'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - '54321:5432'
